Fix API to get language, Age at MRI and removed all the POST, PUT, PATCH requests from the API
Jkat/Loris pull request #7
Opened 2019-04-18 17:08 UTC by cmadjar

what was done for this PR:

1) Remove API v 0.0.1 and 0.0.2 to only support v0.0.3-dev as it is the version needed for the crawler

2) Removed all the POST, PUT, PATCH requests as well as any code that suggested modification of data in the database

3) Modified the query for the candidate to grep the language information stored in the candidate table

4) Modified the query for the session to grep the age at MRI information stored in the session table

5) Modified the query for the MRI QC so that it greps the proper information (a PR was sent to LORIS for a later LORIS release than the one used for Open PREVENT-AD)

6) Updated the documentation of the API that will be shared on the document repository of the open instance of PREVENT-AD for users to understand how to use the API

2019-04-18 21:34 UTC, cmadjar commented on docs/API/LorisRESTAPI_v0.0.3.md
>  ### 4.4 Alternate formats
TODO: modify the API so can download the nii files as well as a format for the imaging download

2019-04-23 17:55 UTC, xlecours commented on htdocs/api/v0.0.3-dev/Candidates.php
> +        $this->error("Create candidate: permission denied");
This error message differ from the other.
Also, it<s not really a permission denied; it's more like 'Operation not permitted'

2019-04-23 17:55 UTC, xlecours approved these changes
I have tested the Language and Age at scan and it work fine. 
I have not tested all the POST/PUT/DELETE to see if they do not work.

2019-04-23 18:40 UTC, christinerogers requested changes
Hi Cecile, found small improvements and a few questions. 

The biggest question: can PUT still be used on the imaging QC ? (e.g. session level) 

In some places I could not comment directly on diff (because the line hadn't been changed), so I've indicated line number in the related comment (nearby but not exactly on the line).

2019-04-23 18:40 UTC, christinerogers commented on docs/API/LorisRESTAPI_v0.0.3.md
> +PUT / PATCH are not supported for candidates.
and POST?

2019-04-23 18:40 UTC, christinerogers commented on docs/API/LorisRESTAPI_v0.0.3.md
> +PUT / PATCH / POST are not supported for this.
"this" -> "for instrument data"

Also, this should be the last line in the subsection, below the success/errors return (for GET)

2019-04-23 18:40 UTC, christinerogers commented on docs/API/LorisRESTAPI_v0.0.3.md
>  It will return a 404 Not Found if the visit label does not exist for this candidate
Switch lines 348 and 350: 
The 404 message applies to GET and so should stay with that text. 
Move the "POST not supported" line down below it.

2019-04-23 18:40 UTC, christinerogers commented on docs/API/LorisRESTAPI_v0.0.3.md
>  }
Remove? PUT statement in 2 places above: 
- [ ] Line 537 (section 4.2)
- [ ] Line 497 (section 4.3.1)

2019-04-24 16:24 UTC, cmadjar commented on docs/API/LorisRESTAPI_v0.0.3.md
> +This document specifies the LORIS REST API.
Perfect! Done!

2019-04-24 16:30 UTC, cmadjar commented on docs/API/LorisRESTAPI_v0.0.3.md
>  document. This document specifies $APIVERSION v0.0.3-dev and it
so far that is the case but we might want to remove it. I'll see

2019-04-24 16:34 UTC, cmadjar commented on docs/API/LorisRESTAPI_v0.0.3.md
>  will respond with a 405 Method Not Allowed response and an appropriate Allow header set (as
done

2019-04-24 16:38 UTC, cmadjar commented on docs/API/LorisRESTAPI_v0.0.3.md
> +so that standard LORIS modules can simply use the API.
Good point! I decided to just remove the sentence. That is good to know for LORIS but a non-LORIS user trying to get the data for the open dataset will be WHAT?? ;). They don't need to know that the modules are using the API.

2019-04-24 16:41 UTC, cmadjar commented on docs/API/LorisRESTAPI_v0.0.3.md
> +If a user is not logged in to LORIS (for instance, in a third party app or a CORS application),
they might need that information when using the script or writing their own scripts if they want to do that.

2019-04-24 16:43 UTC, cmadjar commented on docs/API/LorisRESTAPI_v0.0.3.md
>  by the 3 letter site alias before attempting to pass this regex to a regular expression parser
they will see it in the front. Users won't know about the psc table or the config.xml since we are dealing with it. Since there is only one site, I will just hardcode it here for CONP and simplify the wording. Thanks!

2019-04-24 16:55 UTC, cmadjar commented on docs/API/LorisRESTAPI_v0.0.3.md
> +where V1, V2, etc are the visit labels that are registered for this candidate.
good point. They definitely are not, haha. Changing it

2019-04-24 17:03 UTC, cmadjar commented on docs/API/LorisRESTAPI_v0.0.3.md
>  The "Validity" flag may be missing, if the ValidityEnabled flag is not true for this instrument.
removed it since it will not be used in the open dataset

2019-04-24 17:06 UTC, cmadjar commented on docs/API/LorisRESTAPI_v0.0.3.md
> -### 5.2 Tar Level Data
Haha, I was looking for it in the doc but I just realized that I removed that section so no need to change the header :P .

2019-04-24 17:07 UTC, cmadjar commented on docs/API/LorisRESTAPI_v0.0.3.md
>  ## 2.0 Project API
done

2019-04-24 17:08 UTC, cmadjar commented on docs/API/LorisRESTAPI_v0.0.3.md
>  If the type is "prompt", the user should be prompted to enter the PSCID for new candidates.
I removed that section since people won't be creating candidates and don't need that level of details I think. They would be more confused

2019-04-24 17:09 UTC, cmadjar commented on docs/API/LorisRESTAPI_v0.0.3.md
>  It will return a 404 Not Found if the visit label does not exist for this candidate
nice catch! Done

2019-04-24 17:11 UTC, cmadjar commented on docs/API/LorisRESTAPI_v0.0.3.md
>  }
done! Thanks!

2019-04-24 17:12 UTC, cmadjar commented on docs/API/LorisRESTAPI_v0.0.3.md
> +PUT / PATCH are not supported for candidates.
done

2019-04-24 17:24 UTC, cmadjar commented on htdocs/api/v0.0.3-dev/Candidates.php
> +        $this->error("Create candidate: permission denied");
good point! Will replace all instances with Operation not permitted

2019-04-24 20:34 UTC, merged